@echo off
echo IF YOU HAVE THE PIL IMAGE LIBRARY PYTHON MODULE INSTALL PLEASE REMOVE IT USING "pip uninstall PIL" AS IT CONFLICTS WITH THE IMAGE LIBRARY USED IN THIS PROGRAM.PRESS ENTER TO INSTALL DEPENDENCIES.
pause
pip install Pillow
pip install pyparsing
echo PRESS ENTER TO QUIT
pause